<?php
// $Id: conditional_styles.module,v 1.3 2009/05/25 09:53:55 johnalbin Exp $

/**
 * Implements HOOK_theme().
 */
function conditional_styles_theme($existing, $type, $theme, $path) {
  include_once './' . drupal_get_path('module', 'conditional_styles') . '/conditional_styles.theme.inc';
  return _conditional_styles_theme($existing, $type, $theme, $path);
}

/**
 * Implements MODULE_preprocess_page().
 */
function conditional_styles_preprocess_page(&$vars, $hook) {
  // Append them to $styles and add a $conditional_styles variable.
  $vars['styles'] .= $vars['conditional_styles'] = variable_get('conditional_styles_' . $GLOBALS['theme'], '');
}

/**
 * Implements MODULE_preprocess_maintenance_page().
 */
function conditional_styles_preprocess_maintenance_page(&$vars, $hook) {
  // Append them to $styles and add a $conditional_styles variable.
  $vars['styles'] .= $vars['conditional_styles'] = variable_get('conditional_styles_' . $GLOBALS['theme'], '');
}

/**
 * Implements HOOK_enable().
 */
function conditional_styles_enable() {
  drupal_rebuild_theme_registry();
}
