<?php
/**
 * @file
 * Provides install, upgrade and un-install functions for conditional_styles.
 */

/**
 * Implements hook_uninstall().
 */
function conditional_styles_uninstall() {
  // Delete conditional stylesheets variables.
  $themes = list_themes();
  foreach (array_keys($themes) AS $theme) {
    variable_del('conditional_styles_' . $theme);
    variable_del('conditional_styles_' . $theme . '_rtl');
  }
  // Clear the page cache.
  cache_clear_all();
}
