<?php
// $Id: format_number.install,v 1.1.2.1 2008/11/02 14:20:26 markuspetrux Exp $

/**
 * @file
 * Module installation/uninstallation hooks.
 */

/**
 * Implementation of hook_uninstall().
 */
function format_number_uninstall() {
  // Delete all module variables and then clear the variables cache.
  db_query("DELETE FROM {variable} WHERE name LIKE 'format\_number\_%'");
  cache_clear_all('variables', 'cache');
}
