<?php
// $Id: ad_report.install,v 1.1.4.2 2009/02/23 22:39:05 jeremy Exp $

/**
 * @file
 * Ad Report database functions.
 *
 * Copyright (c) 2008-2009
 *   Jeremy Andrews <jeremy@tag1consulting.com>.
 */

/**
 * Flush the menu cache to register the new ad_report admin menu.
 */
function ad_report_update_5001() {
  $ret = array();
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':
    default:
      $ret[] = update_sql('DELETE FROM {cache_menu}');
  }
  return $ret;
}
